import { defineType, defineField, defineArrayMember } from "sanity";

export const service = defineType({
  name: "service",
  title: "Service",
  type: "document",
  fieldsets: [
    { name: "meta", title: "Metadata", options: { collapsible: true, collapsed: true } },
    { name: "card", title: "Card (appears on /services grid)" },
    { name: "landing", title: "Landing Page Content", options: { collapsible: true } },
    { name: "seo", title: "SEO", options: { collapsible: true, collapsed: true } },
  ],
  fields: [
    defineField({
      name: "title",
      title: "Title",
      type: "string",
      fieldset: "card",
      validation: (R) => R.required(),
    }),
    defineField({
      name: "shortTitle",
      title: "Short Title",
      description: "Used in compact spots like CTAs (e.g. \"Email VA\").",
      type: "string",
      fieldset: "card",
      validation: (R) => R.required(),
    }),
    defineField({
      name: "slug",
      title: "Slug",
      type: "slug",
      options: { source: "title", maxLength: 96 },
      fieldset: "meta",
      validation: (R) => R.required(),
    }),
    defineField({
      name: "iconName",
      title: "Icon",
      type: "string",
      description: "Icon shown on the services grid card.",
      fieldset: "card",
      options: {
        list: [
          { title: "Mail (envelope)", value: "Mail" },
          { title: "Calendar", value: "Calendar" },
          { title: "Share2 (social)", value: "Share2" },
          { title: "Palette (design)", value: "Palette" },
          { title: "Globe (web)", value: "Globe" },
          { title: "Headphones (support)", value: "Headphones" },
          { title: "PenTool (content)", value: "PenTool" },
          { title: "Bot (AI)", value: "Bot" },
          { title: "TrendingUp (growth)", value: "TrendingUp" },
          { title: "Users (team)", value: "Users" },
          { title: "Shield (security)", value: "Shield" },
          { title: "Clock (time)", value: "Clock" },
        ],
      },
      validation: (R) => R.required(),
    }),
    defineField({
      name: "order",
      title: "Sort Order",
      type: "number",
      description: "Lower numbers appear first on the services grid.",
      fieldset: "meta",
      initialValue: 100,
    }),
    defineField({
      name: "description",
      title: "Card Description",
      type: "text",
      rows: 3,
      description: "Short blurb shown on the services grid.",
      fieldset: "card",
      validation: (R) => R.required().max(300),
    }),
    defineField({
      name: "features",
      title: "Card Feature Bullets",
      type: "array",
      of: [defineArrayMember({ type: "string" })],
      fieldset: "card",
      validation: (R) => R.min(1),
    }),
    defineField({
      name: "heroHeadline",
      title: "Hero Headline",
      type: "string",
      fieldset: "landing",
      validation: (R) => R.required(),
    }),
    defineField({
      name: "heroSubheadline",
      title: "Hero Subheadline",
      type: "text",
      rows: 3,
      fieldset: "landing",
      validation: (R) => R.required(),
    }),
    defineField({
      name: "longDescription",
      title: "Long Description (Overview)",
      type: "array",
      of: [defineArrayMember({ type: "text", rows: 4 })],
      fieldset: "landing",
      description: "Each entry becomes a paragraph in the Overview section.",
    }),
    defineField({
      name: "benefits",
      title: "Benefits",
      type: "array",
      fieldset: "landing",
      of: [
        defineArrayMember({
          type: "object",
          name: "benefit",
          fields: [
            defineField({ name: "title", title: "Title", type: "string", validation: (R) => R.required() }),
            defineField({ name: "desc", title: "Description", type: "text", rows: 3, validation: (R) => R.required() }),
          ],
          preview: {
            select: { title: "title", subtitle: "desc" },
          },
        }),
      ],
    }),
    defineField({
      name: "idealFor",
      title: "Ideal For",
      type: "array",
      of: [defineArrayMember({ type: "string" })],
      fieldset: "landing",
      description: "Who this service is designed for.",
    }),
    defineField({
      name: "seoTitle",
      title: "SEO Title",
      type: "string",
      fieldset: "seo",
    }),
    defineField({
      name: "seoDescription",
      title: "SEO Description",
      type: "text",
      rows: 3,
      fieldset: "seo",
      validation: (R) => R.max(200),
    }),
    defineField({
      name: "keywords",
      title: "Keywords",
      type: "array",
      of: [defineArrayMember({ type: "string" })],
      fieldset: "seo",
    }),
  ],
  preview: {
    select: {
      title: "title",
      subtitle: "shortTitle",
    },
  },
  orderings: [
    {
      title: "Sort Order",
      name: "orderAsc",
      by: [{ field: "order", direction: "asc" }],
    },
  ],
});
